spring.application.name=drone

# Configuração do datasource MySQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/drone}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:postgres}

# Configuração do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Configuração da saída de log colorida
spring.output.ansi.enabled=ALWAYS
logging.level.org.hibernate.SQL=DEBUG

logging.level.root=INFO
logging.level.com.example.demo=DEBUG

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.resource=TRACE
